_target_: l2hmc.configs.ConvolutionConfig
# filters: [64, 32, 16, 16, 8]
filters: [8, 16, 16, 32, 64]
sizes: [3, 3, 3, 2, 2]
# filters: [8, 16, 16, 32, 64]
# sizes: [3, 3, 3, 3, 3]
pool: [2, 2, 2, 2, 2]
