"""
params/__init__.py

Author: Sam Foreman
Date: 04/22/2020
"""
from utils.attr_dict import AttrDict

DEFAULT_PARAMS = {
    'space_size': 8,
    'time_size': 8,
    'link_type': 'U1',
    'dim': 2,
    'batch_size': 64,
    'rand': True,
    'num_steps': 5,
    'eps': 0.2,
    'loss_scale': 0.1,
    'lr_init': 0.001,
    'lr_decay_steps': 2000,
    'lr_decay_rate': 0.96,
    'fixed_beta': False,
    'beta_init': 1.,
    'beta_final': 5.,
    'warmup_lr': False,
    'train_steps': 10000,
    'extra_steps': 0,
    'trace': False,
    'save_steps': 5000,
    'print_steps': 10,
    'logging_steps': 100,
    'network_arch': 'generic',
    'network_type': 'GaugeNetwork',
    'num_hidden1': 64,
    'num_hidden2': 128,
    'no_summaries': False,
    'hmc': False,
    'eps_fixed': False,
    'metric': 'cos_diff',
    'std_weight': 1.,
    'aux_weight': 1.,
    'charge_weight': 0.1,
    'plaq_weight': 0.,
    'zero_masks': False,
    'x_scale_weight': 1.,
    'x_translation_weight': 1.,
    'x_transformation_weight': 1.,
    'v_scale_weight': 1.,
    'v_translation_weight': 1.,
    'v_transformation_weight': 1.,
    'use_gaussian_loss': False,
    'use_nnehmc_loss': False,
    'profiler': False,
    'gpu': False,
    'use_bn': False,
    'activation': 'relu',
    'horovod': False,
    'comet': False,
    'dropout_prob': 0.,
    'save_samples': False,
    'save_train_data': True,
    'save_lf': False,
    'clip_value': 0.,
    'restore': False,
    'theta': False,
    'log_dir': None,
    'num_intra_threads': None,
    'num_inter_threads': None,
    'float64': False,
}

GAUGE_PARAMS = {
    'space_size': 8,
    'time_size': 8,
    'link_type': 'U1',
    'dim': 2,
    'batch_size': 64,
    'rand': True,
    #  ------------------- DYNAMICS PARAMS -------------------
    'num_steps': 5,
    'eps': 0.2,
    'fixed_beta': False,
    'beta_init': 2.0,
    'beta_final': 5.0,
    #  ------------------- TRAINING PARAMS -------------------
    'lr_init': 0.001,
    'lr_decay_steps': 1000,
    'lr_decay_rate': 0.96,
    'warmup_lr': False,
    'train_steps': 5000,
    'save_steps': 2500,
    'logging_steps': 2500,
    'print_steps': 1,
    #  ------------------- NETWORK PARAMS -------------------
    'network_arch': 'generic',
    #  'data_format': 'channels_last',
    'num_hidden1': 100,
    'num_hidden2': 100,
    'use_bn': False,
    'dropout_prob': 0.0,
    'clip_value': 0.0,
    'summaries': True,
    #  'save_samples': False,
    'hmc': False,
    #  ------------------- LOSS PARAMS -------------------
    'use_nnehmc_loss': False,
    'use_gaussian_loss': False,
    'loss_scale': 1,
    'std_weight': 1.0,
    'aux_weight': 1.0,
    'charge_weight': 0.0,
    'metric': 'cos_diff',
    # --------------------- NET WEIGHTS -------------------
    'x_scale_weight': 1,
    'x_translation_weight': 1,
    'x_transformation_weight': 1,
    'v_scale_weight': 1,
    'v_translation_weight': 1,
    'v_transformation_weight': 1,
    #  ------------------- MISC. PARAMS -------------------
    'log_dir': None,
    'no_summaries': False,
    'eps_fixed': False,
    'trace': False,
    'profiler': False,
    'gpu': False,
    'horovod': False,
    'comet': False,
    'restore': False,
    'theta': False,
    'num_intra_threads': 0,
    'float64': False,
    'using_hvd': False,
    #####################################
    #  'plot': True
    #  'charge_weight_inference': None,
    #  'print_steps': 1,
    #  'logging_steps': 10,
    #  'plot_lf': False,
    #  'loop_net_weights': False,
    #  'run_hmc': False,
    #  'inverse_loss': True,
    #  'nnehmc_loss': False,
}

GMM_PARAMS = {
    'x_dim': 2,
    'center': 2.,
    'sigma1': 0.02,
    'sigma2': 0.02,
    'num_distributions': 2,
    'arrangement': 'xaxis',
    'size': 1.,
    'batch_size': 200,
    'beta_init': 1./10.,
    'beta_final': 1.,
    'beta_fixed': False,
    'eps_fixed': False,
    'eps': 0.25,
    'hmc': False,
    'network_arch': 'generic',
    'num_steps': 10,
    'use_bn': False,
    'dropout_prob': 0.,
    'num_hidden1': 10,
    'num_hidden2': 10,
    'save_lf': True,
    'loss_scale': 0.1,
    'aux_weight': 1.,
    'clip_value': 0.,
    'lr_init': 1e-3,
    'warmup_lr': False,
    'lr_decay_steps': 1000,
    'lr_decay_rate': 0.96,
    'train_steps': 5000,
    'zero_translation': False,
    'float64': False,
    'trace': False,
    'profiler': False,
    'horovod': False,
    'comet': False,
    'restore': False,
    'theta': False,
    'num_intra_threads': 0,
    'using_hvd': False,
}


GAUGE_FLAGS = AttrDict(GAUGE_PARAMS)
DEFAULT_FLAGS = AttrDict(DEFAULT_PARAMS)
GMM_FLAGS = AttrDict(GMM_PARAMS)
