citation:
   type: article
   container-title: "L2HMC"
   url: https://saforem2.github.io/l2hmc-qcd
author:
  - name: Sam Foreman
    # id: sf
    url: https://samforeman.me
    orcid: 0000-0002-9981-0876
    email: foremans@anl.gov
    # affiliation: 
    #   - name: Argonne National Laboratory
    #     city: Chicago
    #     state: IL
    #     url: https://alcf.anl.gov
date: today
# toc: true
author-title: ""
affiliation-title: ""
published-title: ""
title-block-categories: false
  # - author: true
  # - date: true
  # - affiliation: false
number-sections: false
bibliography: references.bib
# filters:
#   - lua/callouts.lua
# highlight-style:
#   dark: dracula
#   light: dracula-light

execute:
  keep-ipynb: true
  freeze: auto
project:
  render:
    - index.qmd
    - qmd/l2hmc-2DU1.qmd
    - qmd/*.qmd
  type: website
  output-dir: "docs"
  preview:
    port: 4203
website:
  open-graph: true
  repo-url: https://github.com/saforem2/l2hmc-qcd
  repo-actions: [source, edit, issue]
  google-analytics: G-XVM2Y822Y1
  page-navigation: true
  title: "l2hmc-qcd"
  site-url: "https://saforem2.github.io/l2hmc-qcd"
  favicon: "favicon.svg"
  back-to-top-navigation: true
  navbar:
    logo: "./favicon.svg"
    background: "#222222"
    foregound: "#777777"
    right:
    # left:
      - href: qmd/examples.qmd
        text: "[{{< fa solid book >}}]{.red-text} Examples"
      - href: qmd/slides.qmd
        text: "[{{< fa solid person-chalkboard >}}]{.blue-text} Slides"
      - icon: github
        href: https://github.com/saforem2/l2hmc-qcd
        aria-label: GitHub
      # - href: https://saforem2.github.io/lattice23
      #   text: "Slides"
      # - href: qmd/l2hmc-2DU1.qmd
      #   text: "Example: 2D U(1)"
  sidebar: false
## [{{< fa solid hourglass-end >}}]{.blue-text} Appendix
  # sidebar:
  #   style: "floating"
  #   search: true
  #   collapse-level: 2
  #   contents:
  #     - href: index.qmd
  #       text: Home
  #     - href: qmd/l2hmc-2DU1.qmd
  #       text: "Example: 2D U(1)"
  #     - href: qmd/l2hmc-2DU1-alt.qmd
  #       text: "Example: 2D U(1) (alt)"
  #     - href: qmd/pages.qmd
  #       text: Additional Pages
  #     - section: "Documentation"
  #       contents:
  #         - href: qmd/docs.qmd
  #           text: Documentation
  page-footer:
    center: "Copyright 2023, Sam Foreman" 
    left:
      - icon: github
        text: l2hmc-qcd
        href: https://github.com/saforem2/l2hmc-qcd
        aria-label: GitHub
    right:
      - href: https://samforeman.me
        text: "{{< fa solid home >}}"
      - icon: github
        href: https://github.com/saforem2
      - icon: twitter
        href: https://twitter.com/saforem2
      - href: "mailto:///foremans@anl.gov"
        text: "{{< fa regular paper-plane >}}"
      - href: https://www.twitter.com/saforem2
        text: "{{< fa brands twitter >}}"
      - href: https://scholar.google.com/citations?user=vV_1zDwAAAAJ&hl=en
        text: "{{< ai google-scholar >}}"
      - href: https://orcid.org/0000-0002-9981-0876
        text: "{{< ai orcid >}}"
      - href: https://www.last.fm/user/saforem2
        text: "{{< fa brands lastfm >}}"
      - href: https://open.spotify.com/user/saforem2
        text: "{{< fa brands spotify >}}"
      - href: https://www.instagram.com/saforem2
        text: "{{< fa brands instagram >}}"
      - href: https://linkedin.com/in/saforem2
        text: "{{< fa brands linkedin >}}"
format:
  html:
    toc: true
    self-contained: false
    # line-numbers: true
    # code-link: true
    # embed-resources: false
    # self-contained-math: false
    toc-location: right
    grid:
      body-width: 1150px
    # grid:
    #   sidebar-width: 215px
    #   body-width: 975px
    #   margin-width: 150px
    #   gutter-width: 1em
    # embed-resources: true
    page-layout: article
    fig-responsive: true
    anchor-sections: true
    highlight-style: atom-one
    code-overflow: scroll
    code-fold: false
    code-copy: hover
    code-summary: " "
    code-tools:
      source: repo
      toggle: true
      caption: none
    html-math-method: katex
    css:
      - css/default.css
      - css/callouts.css
    theme: 
      dark: 
        - css/common.scss
        - css/dark.scss 
        - css/syntax-dark.scss
      light:
        - css/common.scss
        - css/light.scss
        - css/syntax-light.scss
    # smooth-scroll: true
    citations-hover: true
    footnotes-hover: true
    header-includes: |
      <link href="https://pvinis.github.io/iosevka-webfont/3.4.1/iosevka.css" rel="stylesheet" />
