name: l2hmc
channels:
  - intel
  - defaults
  - conda-forge
dependencies:
  - pandas
  - seaborn
  - matplotlib
  - autograd
  - python=3.7
  - xarray
  - tensorflow=1.15
  - pynvim
  - jedi=0.17
  - arviz
  - pudb
  - pip
  - ipykernel
  - jupyter_contrib_nbextensions
  - jupyterhub
  - joblib
  - nb_conda
