name: l2hmc
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas
  - seaborn
  - matplotlib
  - autograd
  - python=3.7
  - xarray
  - tensorflow>=2.3
  - tensorboard>=2.3
  - arviz
  - pip
  - ipykernel
  - joblib
  - horovod>=0.19.5
