_target_: l2hmc.configs.DynamicsConfig

xshape: [64, 8, 8, 2]
eps: 0.01
nleapfrog: 5
eps_fixed: false
use_ncp: true
use_split_xnets: true
use_separate_networks: true
merge_directions: true
verbose: true
