_target_: l2hmc.configs.DynamicsConfig

eps: 0.125
group: 'U1'
verbose: true
nchains: 128
nleapfrog: 5
eps_hmc: null
use_ncp: true
eps_fixed: false
latvolume: [8, 8]
use_split_xnets: true
merge_directions: true
use_separate_networks: true
