_target_: l2hmc.configs.DynamicsConfig

eps: 0.1
group: 'U1'
verbose: true
nchains: 64
nleapfrog: 3
eps_hmc: null
use_ncp: true
eps_fixed: false
latvolume: [8, 8]
use_split_xnets: true
merge_directions: true
use_separate_networks: true
