_target_: l2hmc.configs.DynamicsConfig

eps: 0.1
group: 'U1'
verbose: true
nchains: 1024
nleapfrog: 8
eps_hmc: null
use_ncp: true
eps_fixed: false
latvolume: [16, 16]
use_split_xnets: true
merge_directions: true
use_separate_networks: true
