_target_: l2hmc.configs.DynamicsConfig

group: 'U1'
nchains: 4
latvolume: [8, 8]
# xshape: [512, 16, 16, 2]
# xshape: [512, 16, 16]
eps: 0.01
nleapfrog: 8
eps_fixed: false
use_ncp: true
use_split_xnets: true
use_separate_networks: true
merge_directions: true
verbose: true
