_target_: l2hmc.configs.DynamicsConfig

eps: 0.06
group: 'SU3'
verbose: true
nchains: 64
nleapfrog: 4
eps_hmc: null
use_ncp: false
eps_fixed: false
latvolume: [4, 4, 4, 4]
use_split_xnets: false
merge_directions: true
use_separate_networks: false
