method: bayes
program: main.py
metric:
  name: dQint_eval.mean
  goal: maximize
parameters:
  net_weights.x.s:
    values: [0.0, 1.0]
  network.units:
    values:
      - [64, 64, 64]
      - [32, 16, 16, 32]
      - [16, 16, 16, 16, 16]
  network.dropout_prob:
    values: [0.0, 0.10, 0.5]
  network.use_batch_norm:
    values: [true, false]
  network.activation_fn:
    values: ["relu", "leaky_relu", "swish"]
  annealing_schedule.beta_init:
    values: [1.0, 2.0, 3.0, 4.0]


command:
  - ${env}
  - ${interpreter}
  - ${program}
  - width=${env:COLUMNS}
  - framework=tensorflow
  - steps.nera=10
  - steps.nepoch=5000
  - steps.test=2500
  - dynamics.group=U1
  - dynamics.nchains=1024
  - dynamics.latvolume=[16, 16]
  - dynamics.nleapfrog=8
  - annealing_schedule.beta_final=4.0
  - ${args_no_hyphens}
