# @package _global_

hydra:
  # launcher:
  #   # override the number of jobs from joblib
  #   n_jobs = 10
  run:
    # Default output paths for all file logs
    dir: "outputs/runs/\
      /${dynamics.group}\
      /${dynamics.latvolume[0]}x${dynamics.latvolume[1]}\
      /nlf-${dynamics.nleapfrog}\
      /beta-${annealing_schedule.beta_final}\
      /merge_directions-${dynamics.merge_directions}\
      /${framework}\
      /${now:%Y-%m-%d}\
      /${now:%H-%M-%S}"
  sweep:
    dir: "outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}"
    # subdir: ${hydra.job.num}
    subdir: ${hydra.job.override_dirname}
