
GAUGE_PARAMS = {                    # default parameters for `GaugeModel`
    #  ------------------- LATTICE PARAMS -------------------
    'space_size': 8,
    'time_size': 8,
    'link_type': 'U1',
    'dim': 2,
    'num_samples': 128,
    'rand': True,
    #  ------------------- DYNAMICS PARAMS -------------------
    'num_steps': 5,
    'eps': 0.2,
    'fixed_beta': False,
    'hmc_beta': None,
    'hmc_eps': None,
    'beta_init': 2.0,
    'beta_final': 5.0,
    'inference': False,
    'beta_inference': None,
    #  ------------------- TRAINING PARAMS -------------------
    'lr_init': 0.001,
    'lr_decay_steps': 1000,
    'lr_decay_rate': 0.96,
    'warmup_lr': False,
    'train_steps': 5000,
    'run_steps': 10000,
    #  ------------------- NETWORK PARAMS -------------------
    'network_arch': 'generic',
    #  'data_format': 'channels_last',
    'num_hidden1': 50,
    'num_hidden2': 50,
    'use_bn': False,
    'dropout_prob': 0.5,
    'clip_value': 0.0,
    'summaries': True,
    'save_samples': False,
    'save_lf': True,
    'eps_fixed': False,
    'hmc': False,
    #  ------------------- LOSS PARAMS -------------------
    'loss_scale': 0.1,
    'std_weight': 1.0,
    'aux_weight': 1.0,
    'charge_weight': 0.0,
    'metric': 'cos_diff',
    #  ------------------- MISC. PARAMS -------------------
    'trace': False,
    'profiler': False,
    'gpu': False,
    'horovod': False,
    'comet': False,
    'restore': False,
    'theta': False,
    'num_intra_threads': 0,
    'float64': False,
    'using_hvd': False,
    #####################################
    #  'plot': True
    #  'charge_weight_inference': None,
    #  'save_steps': 2500,
    #  'print_steps': 1,
    #  'logging_steps': 10,
    #  'plot_lf': False,
    #  'loop_net_weights': False,
    #  'run_hmc': False,
    #  'inverse_loss': True,
    #  'nnehmc_loss': False,
}

GMM_PARAMS = {                # Default parameters for `GaussianMixtureModel`
    'x_dim': 2,
    'centers': 1.,
    'num_distributions': 2,
    'sigma': 0.02,
    'num_samples': 200,
    'diag': True,
    'eps_fixed': False,
    'beta_fixed': False,
    'eps': 0.2,
    'hmc': False,
    'network_arch': 'generic',
    'num_steps': 10,
    'use_bn': False,
    'beta_init': 1./10.,
    'beta_final': 1.,
    'fixed_beta': False,
    'dropout_prob': 0.,
    'num_hidden1': 10,
    'num_hidden2': 10,
    'batch_size': 200,
    'save_lf': True,
    'loss_scale': 0.1,
    'clip_value': 0.,
    'lr_init': 1e-3,
    'warmup_lr': False,
    'lr_decay_steps': 1000,
    'lr_decay_rate': 0.96,
    'train_steps': 5000,
    'zero_translation': False,
    'float64': False,
    'trace': False,
    'profiler': False,
    'horovod': False,
    'comet': False,
    'restore': False,
    'theta': False,
    'num_intra_threads': 0,
    'using_hvd': False,
}
