_target_: l2hmc.configs.LearningRateConfig

# lr_init: 0.01  # for SGD
lr_init: 1e-3  # for Adam
clip_norm:  0 # gradient norm clipping
mode: 'auto'
monitor: 'loss'
patience: 5
cooldown: 0
warmup: 1000
verbose: true
min_lr: 1e-6
factor: 0.98
min_delta: 1e-4
